// exports.map = {
//   2: { algorithm: 'loitering' },
//   13: { algorithm: 'plate' },
//   16: { algorithm: 'aod', attributes: ['time', 'zone', 'cam_name'] },
//   29: { algorithm: 'accident' },
//   35: { algorithm: 'weapon' },
//   39: { algorithm: 'fire', attributes: ['time', 'zone', 'cam_name'] },
//   75: { algorithm: 'trafficsignal' },
//   77: { algorithm: 'stalkingwomanarea' },
//   102: { algorithm: 'kidnapping' },
//   5: {algorithm: 'speed'},
//   0: { algorithm: 'black_white_fr', attributes: ['time', 'name', 'cam_name', 'age', 'gender', 'emotion'] },
// }
exports.map = {
  0: { algorithm: 'black_white_fr', attributes: ['time', 'name', 'cam_name', 'age', 'gender', 'emotion'] },
  2: { algorithm: 'loitering', attributes: ['time', 'dwell', 'cam_name'] },
  5: { algorithm: 'speed' },
  8: { algorithm: 'wrongway' },
  12: { algorithm: 'crowd_count' },
  13: { algorithm: 'plate', attributes: ['time', 'plate', 'cam_name'] },
  16: { algorithm: 'aod', attributes: ['time', 'zone', 'cam_name','object_type'] },
  19: { algorithm: 'violence' },
  26: { algorithm: 'vcount', attributes: ['time', 'vehicle_type', 'cam_name', 'alert'] },
  29: { algorithm: 'accident' },
  35: { algorithm: 'weapon' },
  38: { algorithm: 'collapse' },
  39: { algorithm: 'fire', attributes: ['time', 'zone', 'cam_name'] },
  70: { algorithm: 'congestion' },
  75: { algorithm: 'trafficsignal' },
  77: { algorithm: 'stalkingwomanarea' },
  81: { algorithm: 'InjuryAndBlood' },
  83: { algorithm: 'SmokersGroup' },
  88: { algorithm: 'ZigzagDriving' },
  97: { algorithm: 'UnconsciousWoman' },
  102: { algorithm: 'kidnapping' },
  105: { algorithm: 'WomenViolence' }
}
